# Generated by Django 6.0.4 on 2026-04-17 16:15

import django.core.validators
import django.db.models.deletion
import logistics.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="current_office",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_location",
                to="logistics.postoffice",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="client",
            name="full_name",
            field=models.CharField(blank=True, help_text="ПІБ", max_length=150),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="tracking_number",
            field=models.CharField(
                db_index=True,
                default=logistics.models.get_tracking_number,
                max_length=15,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="parcel",
            name="weight",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Вага від 0.01 до 30.00 кг",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.01")),
                    django.core.validators.MaxValueValidator(Decimal("30.00")),
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="parcel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin_office", models.F("destination_office")), _negated=True
                ),
                name="origin_not_equal_destination",
            ),
        ),
    ]
